// Code generated by protoc-gen-go.
// source: client.proto
// DO NOT EDIT!

/*
Package myproto is a generated protocol buffer package.

It is generated from these files:
	client.proto

It has these top-level messages:
	Client
*/
package myproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Client struct {
	Model            *string `protobuf:"bytes,1,req,name=model" json:"model,omitempty"`
	Action           *string `protobuf:"bytes,2,req,name=action" json:"action,omitempty"`
	IsKeep           *bool   `protobuf:"varint,3,req,name=isKeep" json:"isKeep,omitempty"`
	Content          *string `protobuf:"bytes,4,req,name=content" json:"content,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Client) Reset()                    { *m = Client{} }
func (m *Client) String() string            { return proto.CompactTextString(m) }
func (*Client) ProtoMessage()               {}
func (*Client) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Client) GetModel() string {
	if m != nil && m.Model != nil {
		return *m.Model
	}
	return ""
}

func (m *Client) GetAction() string {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return ""
}

func (m *Client) GetIsKeep() bool {
	if m != nil && m.IsKeep != nil {
		return *m.IsKeep
	}
	return false
}

func (m *Client) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

func init() {
	proto.RegisterType((*Client)(nil), "myproto.Client")
}

var fileDescriptor0 = []byte{
	// 104 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xc9, 0x4c,
	0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf, 0xad, 0x04, 0x33, 0x94, 0x3c,
	0xb8, 0xd8, 0x9c, 0xc1, 0x12, 0x42, 0xbc, 0x5c, 0xac, 0xb9, 0xf9, 0x29, 0xa9, 0x39, 0x12, 0x8c,
	0x0a, 0x4c, 0x1a, 0x9c, 0x42, 0x7c, 0x5c, 0x6c, 0x89, 0xc9, 0x25, 0x99, 0xf9, 0x79, 0x12, 0x4c,
	0x30, 0x7e, 0x66, 0xb1, 0x77, 0x6a, 0x6a, 0x81, 0x04, 0x33, 0x90, 0xcf, 0x21, 0xc4, 0xcf, 0xc5,
	0x9e, 0x9c, 0x9f, 0x57, 0x02, 0xd4, 0x29, 0xc1, 0x02, 0x52, 0x00, 0x08, 0x00, 0x00, 0xff, 0xff,
	0x26, 0xb0, 0xba, 0xf4, 0x61, 0x00, 0x00, 0x00,
}
