// Code generated by protoc-gen-go.
// source: msg_client.proto
// DO NOT EDIT!

/*
Package msgClient is a generated protocol buffer package.

It is generated from these files:
	msg_client.proto

It has these top-level messages:
	Register
*/
package msgClient

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Register struct {
	Uid              *int64  `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	Username         *string `protobuf:"bytes,2,req,name=username" json:"username,omitempty"`
	Roomid           *int64  `protobuf:"varint,3,req,name=roomid" json:"roomid,omitempty"`
	Method           *string `protobuf:"bytes,4,req,name=method" json:"method,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Register) Reset()                    { *m = Register{} }
func (m *Register) String() string            { return proto.CompactTextString(m) }
func (*Register) ProtoMessage()               {}
func (*Register) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Register) GetUid() int64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *Register) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *Register) GetRoomid() int64 {
	if m != nil && m.Roomid != nil {
		return *m.Roomid
	}
	return 0
}

func (m *Register) GetMethod() string {
	if m != nil && m.Method != nil {
		return *m.Method
	}
	return ""
}

func init() {
	proto.RegisterType((*Register)(nil), "msgClient.Register")
}

var fileDescriptor0 = []byte{
	// 115 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0xc8, 0x2d, 0x4e, 0x8f,
	0x4f, 0xce, 0xc9, 0x4c, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x04, 0x8a,
	0x38, 0x83, 0x05, 0x94, 0x3c, 0xb9, 0x38, 0x82, 0x52, 0xd3, 0x33, 0x8b, 0x4b, 0x52, 0x8b, 0x84,
	0xb8, 0xb9, 0x98, 0x4b, 0x33, 0x53, 0x24, 0x18, 0x15, 0x98, 0x34, 0x98, 0x85, 0x04, 0xb8, 0x38,
	0x4a, 0x8b, 0x53, 0x8b, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x98, 0x80, 0x22, 0x9c, 0x42, 0x7c, 0x5c,
	0x6c, 0x45, 0xf9, 0xf9, 0xb9, 0x40, 0x15, 0xcc, 0x60, 0x15, 0x40, 0x7e, 0x6e, 0x6a, 0x49, 0x46,
	0x7e, 0x8a, 0x04, 0x0b, 0x48, 0x1e, 0x10, 0x00, 0x00, 0xff, 0xff, 0xb5, 0x4b, 0x7b, 0x3f, 0x68,
	0x00, 0x00, 0x00,
}
